### PR TITLE
Node doesn't understand Windows' local file URL's

### PR DESCRIPTION
**Pull request by ebpa**

### CODE REVIEW

**Comment by screendriver** [comment]
Thank you very much :+1: 
Could you please fix the ESLint errors?

**Comment by ebpa** [comment]
That should do it.

:-)

**Comment by screendriver** [comment]
Thank you. Merged :sunglasses:

**Comment by ebpa** [comment]
Thanks!

:+1:

**Comment by screendriver** [comment]
Hi @ebpa,

I tried to update some functionality but unfortunately I see now that your pull request destroyed the bundle build on Linux / Mac OS X. Your regex in your function `parseUnescape()` strips the leading slash so paths like `/Users/me/foo/bar` become `Users/me/foo/bar`. So the files can not be imported / loaded anymore.

I try to fix this but I am not the regex guru :confused:

**Comment by screendriver** [comment]
I removed (commented out) windows support temporarily in dd1d30e8975e54997d2f027e95be2cd9ce25cd38

**Pull request merged**
