### PR TITLE
removes lodash dependecies

### PR DESCRIPTION
**Pull request by benib**
This replaces the calls to lodash to get rid of the dependency and thus speed up loading in the browser.

let me know if I miss something or if you think it is not save enough like this.

### CODE REVIEW

**Comment by screendriver** [comment]
Many thanks for the pull request 👍 I thought the same a couple of weeks ago and was about lodash as well (thanks to the shiny new ES2015 methods like `Objec.assign`)
Merged 😎

**Comment by screendriver** [comment]
Oh I see that this pull request conflicts with your previous one #75 
Could you fix the conflict please?

**Comment by benib** [comment]
@screendriver done.

**Comment by screendriver** [comment]
Awesome! Thank you 👍

**Comment by screendriver** [comment]
I've made a `v0.5.1` version for you.

**Comment by benib** [comment]
Very nice. Thanks a lot!

**Pull request merged**
